import json

songs = [
    # BTS Songs (1-15)
    {
        "id": "song_001",
        "title": "Spring Day",
        "artist": "BTS",
        "emotions": ["sadness", "longing", "hope"],
        "theme": "Missing someone and waiting for better days",
        "genre": "K-pop Ballad",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/3cGZLMR53QPtCpZ8R1fqTX",
        "youtube_url": "https://www.youtube.com/watch?v=xEeFrLSkMm8",
        "why_it_helps": "This emotional ballad acknowledges sadness while offering hope that spring will come again."
    },
    {
        "id": "song_002",
        "title": "Life Goes On",
        "artist": "BTS",
        "emotions": ["melancholy", "acceptance", "comfort"],
        "theme": "Finding peace despite hardships",
        "genre": "K-pop Ballad",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/3Pzh926pXggmMe5WVjD0FP",
        "youtube_url": "https://www.youtube.com/watch?v=-5q5mZbe3V8",
        "why_it_helps": "A gentle reminder that life continues and we can find comfort in moving forward."
    },
    {
        "id": "song_003",
        "title": "Not Today",
        "artist": "BTS",
        "emotions": ["determination", "anger", "empowerment"],
        "theme": "Rising up against challenges",
        "genre": "K-pop Hip-Hop",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/0WNGsQ1oH6o3Ym1K3IH6xo",
        "youtube_url": "https://www.youtube.com/watch?v=9DwzBICPhdM",
        "why_it_helps": "An empowering anthem that channels anger into determination to overcome obstacles."
    },
    {
        "id": "song_004",
        "title": "MIC Drop",
        "artist": "BTS",
        "emotions": ["confidence", "triumph", "pride"],
        "theme": "Success and self-confidence",
        "genre": "K-pop Hip-Hop",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/1kJXWDPnYKv3ZMFm0f0TM0",
        "youtube_url": "https://www.youtube.com/watch?v=kTlv5_Bs8aw",
        "why_it_helps": "Boosts confidence and celebrates personal achievements."
    },
    {
        "id": "song_005",
        "title": "Answer: Love Myself",
        "artist": "BTS",
        "emotions": ["self-love", "healing", "acceptance"],
        "theme": "Learning to love yourself",
        "genre": "K-pop Ballad",
        "year": 2018,
        "spotify_url": "https://open.spotify.com/track/3qQbCzHBycnDpGskqOWY0E",
        "youtube_url": "https://www.youtube.com/watch?v=sAB2N3jDd58",
        "why_it_helps": "Encourages self-acceptance and finding peace within yourself."
    },
    {
        "id": "song_006",
        "title": "Magic Shop",
        "artist": "BTS",
        "emotions": ["comfort", "warmth", "healing"],
        "theme": "Finding a safe space for healing",
        "genre": "K-pop Ballad",
        "year": 2018,
        "spotify_url": "https://open.spotify.com/track/0RpddLjWHVKlFbolton0hXo",
        "youtube_url": "https://www.youtube.com/watch?v=vPwaXytZcgI",
        "why_it_helps": "Creates a sense of safety and comfort for emotional healing."
    },
    {
        "id": "song_007",
        "title": "Home",
        "artist": "BTS",
        "emotions": ["longing", "comfort", "connection"],
        "theme": "Finding home in people",
        "genre": "K-pop Ballad",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/3zRA8JOIy1eV8Tc1e0qUuX",
        "youtube_url": "https://www.youtube.com/watch?v=cgXHsSEcsLc",
        "why_it_helps": "Reminds us that home is where we feel loved and accepted."
    },
    {
        "id": "song_008",
        "title": "Permission to Dance",
        "artist": "BTS",
        "emotions": ["joy", "freedom", "celebration"],
        "theme": "Dancing through life's challenges",
        "genre": "K-pop Dance",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/3XYRV7ZSHqIKwbx7vfMYpN",
        "youtube_url": "https://www.youtube.com/watch?v=CbBQLoxSJcc",
        "why_it_helps": "An uplifting song that encourages joy and celebration despite difficulties."
    },
    {
        "id": "song_009",
        "title": "Euphoria",
        "artist": "BTS (Jungkook)",
        "emotions": ["happiness", "love", "ecstasy"],
        "theme": "Pure joy and bliss",
        "genre": "K-pop Dance",
        "year": 2018,
        "spotify_url": "https://open.spotify.com/track/0u8vREQQzn8pcPmh8O2y2d",
        "youtube_url": "https://www.youtube.com/watch?v=kX0vO4vlJuU",
        "why_it_helps": "Creates feelings of euphoria and happiness through uplifting melodies."
    },
    {
        "id": "song_010",
        "title": "Blue & Grey",
        "artist": "BTS",
        "emotions": ["depression", "loneliness", "melancholy"],
        "theme": "Struggling with inner darkness",
        "genre": "K-pop Ballad",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/6dB9RQc0GFxjhAz5u0ilAk",
        "youtube_url": "https://www.youtube.com/watch?v=OgMz1TfGqEg",
        "why_it_helps": "Validates feelings of depression and loneliness, letting you know you're not alone."
    },
    {
        "id": "song_011",
        "title": "Butterfly",
        "artist": "BTS",
        "emotions": ["fear", "vulnerability", "longing"],
        "theme": "Fear of losing someone precious",
        "genre": "K-pop Ballad",
        "year": 2015,
        "spotify_url": "https://open.spotify.com/track/2Pq7VJHqC2O1aMDaUZGvC4",
        "youtube_url": "https://www.youtube.com/watch?v=TfKYWvQb5Kg",
        "why_it_helps": "Expresses fragile emotions and the beauty of vulnerability."
    },
    {
        "id": "song_012",
        "title": "Dynamite",
        "artist": "BTS",
        "emotions": ["joy", "energy", "excitement"],
        "theme": "Living life to the fullest",
        "genre": "K-pop Disco-Pop",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/0t1kP63rueHleOhQkYSXFY",
        "youtube_url": "https://www.youtube.com/watch?v=gdZLi9oWNZg",
        "why_it_helps": "Infectious energy that lifts your mood and makes you want to dance."
    },
    {
        "id": "song_013",
        "title": "Run",
        "artist": "BTS",
        "emotions": ["passion", "recklessness", "youth"],
        "theme": "Running towards dreams despite fear",
        "genre": "K-pop Dance",
        "year": 2015,
        "spotify_url": "https://open.spotify.com/track/68WGdNb2Jvg3LN4aPKBlHG",
        "youtube_url": "https://www.youtube.com/watch?v=5Wn85Ge22FQ",
        "why_it_helps": "Encourages taking risks and embracing youthful passion."
    },
    {
        "id": "song_014",
        "title": "Mikrokosmos",
        "artist": "BTS",
        "emotions": ["wonder", "hope", "connection"],
        "theme": "We all shine like stars",
        "genre": "K-pop Synth-Pop",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/2YV0f0m8lIeT4x6sqoxCb4",
        "youtube_url": "https://www.youtube.com/watch?v=Fw7C6IsDYgI",
        "why_it_helps": "Reminds us that everyone has their own light and value."
    },
    {
        "id": "song_015",
        "title": "The Truth Untold",
        "artist": "BTS (feat. Steve Aoki)",
        "emotions": ["loneliness", "fear", "longing"],
        "theme": "Hiding true self out of fear",
        "genre": "K-pop Ballad",
        "year": 2018,
        "spotify_url": "https://open.spotify.com/track/0nL8cNFV0j0kPgGdZrCu6p",
        "youtube_url": "https://www.youtube.com/watch?v=r5GaAEHvHj0",
        "why_it_helps": "Validates the fear of showing your true self and desire to be loved."
    },
    
    # SEVENTEEN Songs (16-25)
    {
        "id": "song_016",
        "title": "Don't Wanna Cry",
        "artist": "SEVENTEEN",
        "emotions": ["sadness", "heartbreak", "acceptance"],
        "theme": "Letting go of a relationship",
        "genre": "K-pop Ballad",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/4RdhfuVP4qSFOlGAQXYbxd",
        "youtube_url": "https://www.youtube.com/watch?v=zEkg4GBQumc",
        "why_it_helps": "Validates the pain of letting go while moving toward acceptance."
    },
    {
        "id": "song_017",
        "title": "Good to Me",
        "artist": "SEVENTEEN",
        "emotions": ["happiness", "gratitude", "warmth"],
        "theme": "Appreciating positive relationships",
        "genre": "K-pop R&B",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/2O3ggSCUfhKbm8ZLwBqzQ3",
        "youtube_url": "https://www.youtube.com/watch?v=m8TcJHnZUkw",
        "why_it_helps": "Focuses on gratitude and positive connections with others."
    },
    {
        "id": "song_018",
        "title": "Home;Run",
        "artist": "SEVENTEEN",
        "emotions": ["excitement", "energy", "confidence"],
        "theme": "Taking bold action",
        "genre": "K-pop Swing",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/1DFixXjH7nPp2ntxFgMVyy",
        "youtube_url": "https://www.youtube.com/watch?v=UB4FzllQCyc",
        "why_it_helps": "Energizing and confidence-boosting with a unique retro vibe."
    },
    {
        "id": "song_019",
        "title": "Left & Right",
        "artist": "SEVENTEEN",
        "emotions": ["happiness", "playfulness", "joy"],
        "theme": "Carefree fun and friendship",
        "genre": "K-pop Dance",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/6bnF93Rx87YqUBLSgjiMU8",
        "youtube_url": "https://www.youtube.com/watch?v=HdZdxocqzq4",
        "why_it_helps": "Pure fun that makes you want to dance and forget your worries."
    },
    {
        "id": "song_020",
        "title": "Hug",
        "artist": "SEVENTEEN",
        "emotions": ["comfort", "warmth", "support"],
        "theme": "Being there for someone",
        "genre": "K-pop Ballad",
        "year": 2015,
        "spotify_url": "https://open.spotify.com/track/6C4dYvmJlqcKp8P6f5m7f8",
        "youtube_url": "https://www.youtube.com/watch?v=j69PgNYFHfM",
        "why_it_helps": "Offers virtual comfort like a warm hug from a friend."
    },
    {
        "id": "song_021",
        "title": "Very Nice",
        "artist": "SEVENTEEN",
        "emotions": ["happiness", "excitement", "love"],
        "theme": "Joyful love and excitement",
        "genre": "K-pop Dance",
        "year": 2016,
        "spotify_url": "https://open.spotify.com/track/1WJq3WpapBLxiPBxWM9xJh",
        "youtube_url": "https://www.youtube.com/watch?v=J-wFp43XOrA",
        "why_it_helps": "Infectious energy and happiness that's impossible not to feel."
    },
    {
        "id": "song_022",
        "title": "Anyone",
        "artist": "SEVENTEEN",
        "emotions": ["longing", "yearning", "passion"],
        "theme": "Intense desire and yearning",
        "genre": "K-pop R&B",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/0VfKu3jTlYBQJUhQZBfUmm",
        "youtube_url": "https://www.youtube.com/watch?v=jjCBYlzwaY8",
        "why_it_helps": "Channeling intense emotions into powerful musical expression."
    },
    {
        "id": "song_023",
        "title": "Rock with You",
        "artist": "SEVENTEEN",
        "emotions": ["romance", "warmth", "connection"],
        "theme": "Dancing together through life",
        "genre": "K-pop Disco",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/7nKtfqG0MaEZWYzZKKdkcJ",
        "youtube_url": "https://www.youtube.com/watch?v=WpuatuzSDK4",
        "why_it_helps": "Romantic and uplifting with a smooth, comforting vibe."
    },
    {
        "id": "song_024",
        "title": "Kidult",
        "artist": "SEVENTEEN",
        "emotions": ["nostalgia", "comfort", "growth"],
        "theme": "Growing up while staying young at heart",
        "genre": "K-pop Ballad",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/0V9E0nBb1bN4MN9RlSPBSW",
        "youtube_url": "https://www.youtube.com/watch?v=TlyqGwSo_70",
        "why_it_helps": "Comforting message about embracing both growth and inner child."
    },
    {
        "id": "song_025",
        "title": "Thanks",
        "artist": "SEVENTEEN",
        "emotions": ["gratitude", "warmth", "appreciation"],
        "theme": "Thanking those who matter",
        "genre": "K-pop Ballad",
        "year": 2018,
        "spotify_url": "https://open.spotify.com/track/3znoE6N1XXyaXX5BdFqUhT",
        "youtube_url": "https://www.youtube.com/watch?v=7xKwpPQiPGs",
        "why_it_helps": "Heartfelt expression of gratitude that reminds us of our support system."
    },
    
    # IU Songs (26-35)
    {
        "id": "song_026",
        "title": "Love Poem",
        "artist": "IU",
        "emotions": ["love", "comfort", "warmth"],
        "theme": "Universal love and comfort",
        "genre": "K-pop Ballad",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/7qksdtbzFTnXfrh1jzrEDJ",
        "youtube_url": "https://www.youtube.com/watch?v=iOKRYIMhaDk",
        "why_it_helps": "Soothing ballad that offers comfort like a warm embrace."
    },
    {
        "id": "song_027",
        "title": "Through the Night",
        "artist": "IU",
        "emotions": ["longing", "hope", "comfort"],
        "theme": "Wishing well for someone far away",
        "genre": "K-pop Ballad",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/7e0b9oZQZxPGvVAKNKZCjc",
        "youtube_url": "https://www.youtube.com/watch?v=BzYnNdJhZQw",
        "why_it_helps": "Gentle and calming, perfect for peaceful reflection."
    },
    {
        "id": "song_028",
        "title": "Blueming",
        "artist": "IU",
        "emotions": ["happiness", "love", "excitement"],
        "theme": "Blooming with new love",
        "genre": "K-pop Pop",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/0aiyYgQBluwSuZ0LnRQr5K",
        "youtube_url": "https://www.youtube.com/watch?v=D1PvIWdJ8xo",
        "why_it_helps": "Light and cheerful, capturing the excitement of new beginnings."
    },
    {
        "id": "song_029",
        "title": "Palette",
        "artist": "IU (feat. G-DRAGON)",
        "emotions": ["self-acceptance", "maturity", "confidence"],
        "theme": "Being comfortable with yourself",
        "genre": "K-pop R&B",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/6yVXxPtFf5BQxfmYjYD0eS",
        "youtube_url": "https://www.youtube.com/watch?v=d9IxdwEFk1c",
        "why_it_helps": "Celebrates self-discovery and being comfortable in your own skin."
    },
    {
        "id": "song_030",
        "title": "Good Day",
        "artist": "IU",
        "emotions": ["happiness", "energy", "optimism"],
        "theme": "Bright and cheerful day",
        "genre": "K-pop Dance",
        "year": 2010,
        "spotify_url": "https://open.spotify.com/track/1DFnBCJN6MxPssgPtsdIWG",
        "youtube_url": "https://www.youtube.com/watch?v=jeqdYqsrsA0",
        "why_it_helps": "Iconic uplifting song that brings instant positivity."
    },
    {
        "id": "song_031",
        "title": "eight",
        "artist": "IU (feat. SUGA)",
        "emotions": ["nostalgia", "sadness", "hope"],
        "theme": "Remembering youth and lost time",
        "genre": "K-pop Indie",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/09w9cWpUZrxU6f5rkjx3V0",
        "youtube_url": "https://www.youtube.com/watch?v=TgOu00Mf3kI",
        "why_it_helps": "Poignant reflection on memory and growth with hopeful undertones."
    },
    {
        "id": "song_032",
        "title": "Lilac",
        "artist": "IU",
        "emotions": ["bittersweet", "farewell", "growth"],
        "theme": "Saying goodbye to the past",
        "genre": "K-pop Dance-Pop",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/5xDJRbYko5JMZgNJY7sK2D",
        "youtube_url": "https://www.youtube.com/watch?v=v7bnOxV4jAc",
        "why_it_helps": "Bittersweet but empowering song about moving forward."
    },
    {
        "id": "song_033",
        "title": "Ending Scene",
        "artist": "IU",
        "emotions": ["heartbreak", "acceptance", "melancholy"],
        "theme": "The end of a relationship",
        "genre": "K-pop Ballad",
        "year": 2017,
        "spotify_url": "https://open.spotify.com/track/0Dm6xLYFQCRFqOPejT1mBt",
        "youtube_url": "https://www.youtube.com/watch?v=Rh5ok0ljrzA",
        "why_it_helps": "Beautifully captures the pain of endings with grace and acceptance."
    },
    {
        "id": "song_034",
        "title": "Celebrity",
        "artist": "IU",
        "emotions": ["confidence", "uniqueness", "self-worth"],
        "theme": "Recognizing your own worth",
        "genre": "K-pop Pop",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/0Ov06S4w2oTq9f3zf15XtH",
        "youtube_url": "https://www.youtube.com/watch?v=0-q1KafFCLU",
        "why_it_helps": "Empowering message about recognizing your unique value."
    },
    {
        "id": "song_035",
        "title": "My Sea",
        "artist": "IU",
        "emotions": ["introspection", "calm", "acceptance"],
        "theme": "Finding peace within yourself",
        "genre": "K-pop Ballad",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/6QdPqGC3l1fy9JKiZCgeGa",
        "youtube_url": "https://www.youtube.com/watch?v=DYmN6O4M_Bo",
        "why_it_helps": "Peaceful and introspective, encouraging self-reflection."
    },
    
    # BLACKPINK Songs (36-40)
    {
        "id": "song_036",
        "title": "Stay",
        "artist": "BLACKPINK",
        "emotions": ["longing", "vulnerability", "love"],
        "theme": "Asking someone to stay",
        "genre": "K-pop Ballad",
        "year": 2016,
        "spotify_url": "https://open.spotify.com/track/04qL0ht0KKyv8cMfHLCw2K",
        "youtube_url": "https://www.youtube.com/watch?v=FzVR_fymZw4",
        "why_it_helps": "Soft and vulnerable, expressing the desire for connection."
    },
    {
        "id": "song_037",
        "title": "How You Like That",
        "artist": "BLACKPINK",
        "emotions": ["empowerment", "confidence", "resilience"],
        "theme": "Rising stronger after falling",
        "genre": "K-pop Hip-Hop",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/4Ws314Ylb27BVsvlW7dWtK",
        "youtube_url": "https://www.youtube.com/watch?v=ioNng23DkIM",
        "why_it_helps": "Powerful anthem about bouncing back stronger."
    },
    {
        "id": "song_038",
        "title": "Lovesick Girls",
        "artist": "BLACKPINK",
        "emotions": ["heartbreak", "resilience", "hope"],
        "theme": "Love despite pain",
        "genre": "K-pop Dance-Pop",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/4Cmr0ZOHLJbYp5teFf46Dz",
        "youtube_url": "https://www.youtube.com/watch?v=dyRsYk0LyA8",
        "why_it_helps": "Acknowledges heartbreak while maintaining hope for love."
    },
    {
        "id": "song_039",
        "title": "Pink Venom",
        "artist": "BLACKPINK",
        "emotions": ["confidence", "power", "attitude"],
        "theme": "Fierce confidence and power",
        "genre": "K-pop Hip-Hop",
        "year": 2022,
        "spotify_url": "https://open.spotify.com/track/7gRFDGEzF9UkBV233yv2dc",
        "youtube_url": "https://www.youtube.com/watch?v=gQlMMD8auMs",
        "why_it_helps": "Bold and fierce energy that boosts confidence."
    },
    {
        "id": "song_040",
        "title": "You Never Know",
        "artist": "BLACKPINK",
        "emotions": ["vulnerability", "strength", "defiance"],
        "theme": "Hidden struggles and inner strength",
        "genre": "K-pop Ballad",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/1T1JoKGgOQRmeVp2qj1KxW",
        "youtube_url": "https://www.youtube.com/watch?v=b3rjlYUBz5s",
        "why_it_helps": "Addresses hidden pain while asserting inner strength."
    },
    
    # NewJeans, TXT, Stray Kids, aespa (41-50)
    {
        "id": "song_041",
        "title": "Hype Boy",
        "artist": "NewJeans",
        "emotions": ["happiness", "love", "excitement"],
        "theme": "Crush and excitement",
        "genre": "K-pop R&B",
        "year": 2022,
        "spotify_url": "https://open.spotify.com/track/0Je5S5cIZn86yLCxuwQIS1",
        "youtube_url": "https://www.youtube.com/watch?v=11cta61wi0g",
        "why_it_helps": "Fresh and exciting vibe that lifts your mood."
    },
    {
        "id": "song_042",
        "title": "OMG",
        "artist": "NewJeans",
        "emotions": ["excitement", "surprise", "joy"],
        "theme": "Overwhelming excitement",
        "genre": "K-pop Dance",
        "year": 2023,
        "spotify_url": "https://open.spotify.com/track/3lnHDV0A5W07QK4cZS7RHg",
        "youtube_url": "https://www.youtube.com/watch?v=sVTy_wmn5SU",
        "why_it_helps": "Energetic and fun, perfect for boosting energy."
    },
    {
        "id": "song_043",
        "title": "Blue Hour",
        "artist": "TOMORROW X TOGETHER",
        "emotions": ["nostalgia", "magic", "hope"],
        "theme": "Cherishing magical moments",
        "genre": "K-pop Dance-Pop",
        "year": 2020,
        "spotify_url": "https://open.spotify.com/track/1M3vMFmtXJtR7C6Wkxv3DV",
        "youtube_url": "https://www.youtube.com/watch?v=Vd9QkWsd5p4",
        "why_it_helps": "Captures the magic of precious moments with friends."
    },
    {
        "id": "song_044",
        "title": "0X1=LOVESONG",
        "artist": "TOMORROW X TOGETHER",
        "emotions": ["loneliness", "hope", "connection"],
        "theme": "Finding love in loneliness",
        "genre": "K-pop Emo-Rock",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/0x9G8KZxQhhhjYDRKOBKvz",
        "youtube_url": "https://www.youtube.com/watch?v=d5bbqKYu51w",
        "why_it_helps": "Raw emotion about finding connection when feeling alone."
    },
    {
        "id": "song_045",
        "title": "Levanter",
        "artist": "Stray Kids",
        "emotions": ["acceptance", "letting go", "growth"],
        "theme": "Moving on and growing",
        "genre": "K-pop Dance",
        "year": 2019,
        "spotify_url": "https://open.spotify.com/track/23PdNAWTWMDOXBhPG4kFr0",
        "youtube_url": "https://www.youtube.com/watch?v=Fpgd3ac3_nM",
        "why_it_helps": "About accepting change and moving forward positively."
    },
    {
        "id": "song_046",
        "title": "Maniac",
        "artist": "Stray Kids",
        "emotions": ["confidence", "uniqueness", "defiance"],
        "theme": "Embracing your unique self",
        "genre": "K-pop Hip-Hop",
        "year": 2022,
        "spotify_url": "https://open.spotify.com/track/2KPxkMPjWjd1RWZjJpQyyz",
        "youtube_url": "https://www.youtube.com/watch?v=kmYHZ_LjNgQ",
        "why_it_helps": "Celebrates being different and standing out boldly."
    },
    {
        "id": "song_047",
        "title": "Blueprint",
        "artist": "Stray Kids",
        "emotions": ["determination", "ambition", "confidence"],
        "theme": "Building your own path",
        "genre": "K-pop Hip-Hop",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/6sEJJIbLFBdMJT6GdxgfPY",
        "youtube_url": "https://www.youtube.com/watch?v=LYJDf9oPQ-0",
        "why_it_helps": "Motivating song about creating your own destiny."
    },
    {
        "id": "song_048",
        "title": "Dreams Come True",
        "artist": "aespa",
        "emotions": ["hope", "optimism", "joy"],
        "theme": "Dreams becoming reality",
        "genre": "K-pop Dance-Pop",
        "year": 2021,
        "spotify_url": "https://open.spotify.com/track/1zBCGfXhkM1L0XgvW1KFGJ",
        "youtube_url": "https://www.youtube.com/watch?v=xvK5OuDqy-c",
        "why_it_helps": "Uplifting message about dreams coming true."
    },
    {
        "id": "song_049",
        "title": "Thirsty",
        "artist": "aespa",
        "emotions": ["desire", "passion", "intensity"],
        "theme": "Intense desire and ambition",
        "genre": "K-pop R&B",
        "year": 2023,
        "spotify_url": "https://open.spotify.com/track/4qHbB3Ky6q1z7MJW9KLbfF",
        "youtube_url": "https://www.youtube.com/watch?v=1CjJOKVQEXc",
        "why_it_helps": "Channels intense feelings into powerful expression."
    },
    {
        "id": "song_050",
        "title": "Better Things",
        "artist": "aespa",
        "emotions": ["hope", "optimism", "moving on"],
        "theme": "Better days ahead",
        "genre": "K-pop Pop",
        "year": 2023,
        "spotify_url": "https://open.spotify.com/track/7y0lLbXQTBfH4h62dxmFdK",
        "youtube_url": "https://www.youtube.com/watch?v=Gn4kSZ0j1vU",
        "why_it_helps": "Hopeful message about moving towards better times."
    }
]

# Write to JSON file
with open('data/songs.json', 'w', encoding='utf-8') as f:
    json.dump(songs, f, indent=2, ensure_ascii=False)

print(f"Created songs.json with {len(songs)} K-pop songs!")
